# Generated by Django 2.2.16 on 2022-10-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221006_1956'),
        ('reviews', '0010_auto_20221008_1253'),
    ]

    operations = [
    ]
